version: 2
updates:
  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /scrapers/cheerio-worker
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /scrapers/import-worker
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /scrapers/novel-worker
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /scrapers/webtoons
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore
    labels:
      - dependencies
