import type { Media } from './types';

export const mockTrending: Media[] = [
  { id: "1", title: "Inception", type: "film", year: 2010, rating: 8.8, posterUrl: "https://image.tmdb.org/t/p/w500/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg", slug: "inception", synopsis: "Un voleur spécialisé dans l'extraction de secrets utilise une technologie de partage de rêves pour implanter une idée dans l'esprit d'un PDG.", genres: ["Action", "Science-Fiction", "Thriller"] },
  { id: "2", title: "Breaking Bad", type: "serie", year: 2008, rating: 9.5, posterUrl: "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg", slug: "breaking-bad", synopsis: "Un professeur de chimie atteint d'un cancer se lance dans la fabrication de méthamphétamine pour assurer l'avenir financier de sa famille.", genres: ["Crime", "Drame", "Thriller"] },
  { id: "3", title: "Arcane", type: "anime", year: 2021, rating: 9.0, posterUrl: "https://image.tmdb.org/t/p/w500/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg", slug: "arcane", synopsis: "Dans les villes jumelles de Piltover et Zaun, deux sœurs se battent dans des camps opposés d'un conflit entre technologies magiques et croyances.", genres: ["Animation", "Action", "Aventure"] },
  { id: "4", title: "Dune: Part Two", type: "film", year: 2024, rating: 8.7, posterUrl: "https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg", slug: "dune-part-two", synopsis: "Paul Atreides s'unit aux Fremen pour venger sa famille et empêcher une terrible catastrophe.", genres: ["Science-Fiction", "Aventure", "Drame"] },
  { id: "5", title: "Solo Leveling", type: "anime", year: 2024, rating: 8.5, posterUrl: "https://image.tmdb.org/t/p/w500/geCRueV3ElhRTr0xtJuEWJt6dJ1.jpg", slug: "solo-leveling", synopsis: "Dans un monde de chasseurs de monstres, le plus faible d'entre eux obtient un pouvoir unique qui lui permet de monter en niveau.", genres: ["Action", "Fantastique", "Animation"] },
  { id: "6", title: "Spider-Verse", type: "film", year: 2023, rating: 8.9, posterUrl: "https://image.tmdb.org/t/p/w500/8Vt6mWEReoyU2GWJznK12GzJz1.jpg", slug: "spider-verse", synopsis: "Miles Morales voyage à travers le multivers pour rencontrer d'autres Spider-Man.", genres: ["Animation", "Action", "Aventure"] },
];

export const mockFilms: Media[] = [
  { id: "f1", title: "Interstellar", type: "film", year: 2014, rating: 8.6, posterUrl: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg", slug: "interstellar", synopsis: "Un groupe d'explorateurs voyage à travers un trou de ver spatial pour assurer la survie de l'humanité.", genres: ["Science-Fiction", "Aventure", "Drame"] },
  { id: "f2", title: "The Dark Knight", type: "film", year: 2008, rating: 9.0, posterUrl: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux9JwNTSFM1N9q21L.jpg", slug: "the-dark-knight", synopsis: "Batman affronte le Joker, un génie du crime qui plonge Gotham dans le chaos.", genres: ["Action", "Crime", "Drame"] },
  { id: "f3", title: "Oppenheimer", type: "film", year: 2023, rating: 8.4, posterUrl: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg", slug: "oppenheimer", synopsis: "L'histoire du physicien J. Robert Oppenheimer et son rôle dans la création de la bombe atomique.", genres: ["Drame", "Histoire", "Thriller"] },
  { id: "f4", title: "Pulp Fiction", type: "film", year: 1994, rating: 8.9, posterUrl: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg", slug: "pulp-fiction", synopsis: "Les destins de plusieurs criminels de Los Angeles s'entremêlent dans cette fresque du crime.", genres: ["Crime", "Drame", "Thriller"] },
  { id: "f5", title: "The Matrix", type: "film", year: 1999, rating: 8.7, posterUrl: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg", slug: "the-matrix", synopsis: "Un hacker découvre que la réalité n'est qu'une simulation et rejoint une rébellion pour libérer l'humanité.", genres: ["Action", "Science-Fiction"] },
  { id: "f6", title: "Gladiator", type: "film", year: 2000, rating: 8.5, posterUrl: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgpniq.jpg", slug: "gladiator", synopsis: "Un général romain trahi cherche à venger sa famille dans l'arène du Colisée.", genres: ["Action", "Aventure", "Drame"] },
  { id: "f7", title: "The Godfather", type: "film", year: 1972, rating: 9.2, posterUrl: "https://image.tmdb.org/t/p/w500/3bhkrj1Dndf4qVP1VO1vwsG4pOi.jpg", slug: "the-godfather", synopsis: "Le patriarche d'une famille mafieuse cherche à transmettre son empire à son fils.", genres: ["Crime", "Drame"] },
  { id: "f8", title: "Parasite", type: "film", year: 2019, rating: 8.5, posterUrl: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg", slug: "parasite", synopsis: "Une famille pauvre s'infiltre dans la vie d'une famille riche avec des conséquences inattendues.", genres: ["Drame", "Thriller", "Comédie"] },
  { id: "f9", title: "The Shawshank Redemption", type: "film", year: 1994, rating: 9.3, posterUrl: "https://image.tmdb.org/t/p/w500/q6y0GoSWr9RRK0LbKy8E3ZW7X8K.jpg", slug: "the-shawshank-redemption", synopsis: "Un banquier condamné à perpétuité entretient l'espoir et se lie d'amitié dans l'univers carcéral.", genres: ["Drame"] },
  { id: "f10", title: "Fight Club", type: "film", year: 1999, rating: 8.8, posterUrl: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg", slug: "fight-club", synopsis: "Un employé de bureau insomniaque crée un club de combat clandestin qui dégénère en mouvement anarchiste.", genres: ["Drame", "Thriller"] },
];

export const mockSeries: Media[] = [
  { id: "s1", title: "Better Call Saul", type: "serie", year: 2015, rating: 9.0, posterUrl: "https://image.tmdb.org/t/p/w500/fC2HDm5t0kHl7mTm7jxMR31b7by.jpg", slug: "better-call-saul", synopsis: "Les aventures de Jimmy McGill, un petit avocat qui deviendra l'impitoyable Saul Goodman.", genres: ["Crime", "Drame", "Comédie"] },
  { id: "s2", title: "Succession", type: "serie", year: 2018, rating: 8.9, posterUrl: "https://image.tmdb.org/t/p/w500/7HW47XbkNQ5fiwQFYGWdw9gs144.jpg", slug: "succession", synopsis: "La famille Roy se déchire pour le contrôle d'un empire médiatique mondial.", genres: ["Drame", "Comédie"] },
  { id: "s3", title: "The Last of Us", type: "serie", year: 2023, rating: 8.9, posterUrl: "https://image.tmdb.org/t/p/w500/uKvVjHNqB5VsLKGzJPTH7fKbUykS6K.jpg", slug: "the-last-of-us", synopsis: "Dans un monde post-apocalyptique, un survivant doit protéger une jeune fille immunisée contre un virus.", genres: ["Action", "Aventure", "Drame"] },
  { id: "s4", title: "The Boys", type: "serie", year: 2019, rating: 8.7, posterUrl: "https://image.tmdb.org/t/p/w500/stTEycfG9928HYGEISBFaG1ngjM.jpg", slug: "the-boys", synopsis: "Une équipe de justiciers affronte des super-héros corrompus qui abusent de leurs pouvoirs.", genres: ["Action", "Comédie", "Science-Fiction"] },
  { id: "s5", title: "Stranger Things", type: "serie", year: 2016, rating: 8.7, posterUrl: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg", slug: "stranger-things", synopsis: "Un groupe d'enfants découvre des phénomènes surnaturels dans leur petite ville des années 80.", genres: ["Science-Fiction", "Horreur", "Mystère"] },
  { id: "s6", title: "Chernobyl", type: "serie", year: 2019, rating: 9.4, posterUrl: "https://image.tmdb.org/t/p/w500/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg", slug: "chernobyl", synopsis: "La catastrophe nucléaire de Tchernobyl et les efforts pour en limiter les conséquences.", genres: ["Drame", "Histoire", "Thriller"] },
  { id: "s7", title: "Game of Thrones", type: "serie", year: 2011, rating: 9.2, posterUrl: "https://image.tmdb.org/t/p/w500/7WUHnWGx5OUyxBSDbod2FW1oP7a.jpg", slug: "game-of-thrones", synopsis: "Dans un monde fantastique, des familles nobles se disputent le trône de fer.", genres: ["Action", "Aventure", "Fantastique"] },
  { id: "s8", title: "The Office", type: "serie", year: 2005, rating: 8.9, posterUrl: "https://image.tmdb.org/t/p/w500/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg", slug: "the-office", synopsis: "Le quotidien loufoque des employés d'une entreprise de papier en Pennsylvanie.", genres: ["Comédie"] },
  { id: "s9", title: "Dark", type: "serie", year: 2017, rating: 8.8, posterUrl: "https://image.tmdb.org/t/p/w500/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg", slug: "dark", synopsis: "Les disparitions d'enfants dans une petite ville allemande révèlent des secrets temporels.", genres: ["Science-Fiction", "Mystère", "Drame"] },
  { id: "s10", title: "Peaky Blinders", type: "serie", year: 2013, rating: 8.8, posterUrl: "https://image.tmdb.org/t/p/w500/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg", slug: "peaky-blinders", synopsis: "Un gangster de Birmingham impose sa loi dans l'Angleterre des années 1920.", genres: ["Crime", "Drame"], legalLinks: [{ platform: "Netflix", url: "https://netflix.com", type: "stream" }] },
];

export const mockAnimes: Media[] = [
  { id: "a1", title: "Attack on Titan", type: "anime", year: 2013, rating: 9.1, posterUrl: "https://image.tmdb.org/t/p/w500/hTP1DtbTV7Ivg13vURu98OjrZp8.jpg", slug: "attack-on-titan", synopsis: "L'humanité se bat pour sa survie contre des géants dévoreurs d'hommes.", genres: ["Action", "Fantastique", "Drame"] },
  { id: "a2", title: "One Piece", type: "anime", year: 1999, rating: 8.9, posterUrl: "https://image.tmdb.org/t/p/w500/e3NBGiAifW9Xt8xD5tpARskjccO.jpg", slug: "one-piece", synopsis: "Un jeune pirate cherche le trésor ultime, le One Piece, pour devenir le Roi des Pirates.", genres: ["Action", "Aventure", "Comédie"] },
  { id: "a3", title: "Demon Slayer", type: "anime", year: 2019, rating: 8.7, posterUrl: "https://image.tmdb.org/t/p/w500/xUAkNcVbjl5RL6az68VdrdWjSTp.jpg", slug: "demon-slayer", synopsis: "Un jeune garçon devient pourfendeur de démons pour venger sa famille et sauver sa sœur.", genres: ["Action", "Fantastique", "Animation"] },
  { id: "a4", title: "Jujutsu Kaisen", type: "anime", year: 2020, rating: 8.7, posterUrl: "https://image.tmdb.org/t/p/w500/hFWP5HkbVEe40hrXgtCeQxoccHE.jpg", slug: "jujutsu-kaisen", synopsis: "Un lycéen avale un doigt maudit et rejoint une école de sorcellerie pour combattre des fléaux.", genres: ["Action", "Fantastique", "Animation"] },
  { id: "a5", title: "Cowboy Bebop", type: "anime", year: 1998, rating: 8.9, posterUrl: "https://image.tmdb.org/t/p/w500/hyqxFOvxMZM0V0R7ShEZnj7wvL8.jpg", slug: "cowboy-bebop", synopsis: "Des chasseurs de primes voyagent à travers le système solaire à bord du Bebop.", genres: ["Action", "Science-Fiction", "Animation"] },
  { id: "a6", title: "FMA Brotherhood", type: "anime", year: 2009, rating: 9.1, posterUrl: "https://image.tmdb.org/t/p/w500/1E1tUvSn4cGbKMCk6hH3A5mYR0Y.jpg", slug: "fma-brotherhood", synopsis: "Deux frères alchimistes cherchent la pierre philosophale pour restaurer leurs corps perdus.", genres: ["Action", "Aventure", "Fantastique"] },
  { id: "a7", title: "Death Note", type: "anime", year: 2006, rating: 9.0, posterUrl: "https://image.tmdb.org/t/p/w500/g8hfGLnjU9bENpG6CnP9wJGybQM.jpg", slug: "death-note", synopsis: "Un lycéen découvre un carnet qui toute personne dont le nom y est inscrit.", genres: ["Mystère", "Thriller", "Animation"] },
  { id: "a8", title: "Hunter x Hunter", type: "anime", year: 2011, rating: 9.0, posterUrl: "https://image.tmdb.org/t/p/w500/dWCL2X1kGZwNh9N7lRkYeDHkHVa.jpg", slug: "hunter-x-hunter", synopsis: "Un jeune garçon part en quête de son père et devient chasseur dans un monde dangereux.", genres: ["Action", "Aventure", "Fantastique"] },
];

export const mockGames: Media[] = [
  { id: "g1", title: "The Legend of Zelda: Tears of the Kingdom", type: "jeu", year: 2023, rating: 9.5, posterUrl: "https://image.tmdb.org/t/p/w500/xxkdQK7I63WQkPNfZVPEsYw0P2r.jpg", slug: "zelda-tears-of-the-kingdom", synopsis: "Link explore les cieux et les profondeurs d'Hyrule pour vaincre un mal ancien.", genres: ["Action", "Aventure"] },
  { id: "g2", title: "Baldur's Gate 3", type: "jeu", year: 2023, rating: 9.6, posterUrl: "https://image.tmdb.org/t/p/w500/9FFUkCOAYnMniFC8JbMxiFLJ4vO.jpg", slug: "baldurs-gate-3", synopsis: "Un RPG épique basé sur Donjons & Dragons où vos choix façonnent le monde.", genres: ["RPG", "Fantastique", "Aventure"] },
  { id: "g3", title: "Elden Ring", type: "jeu", year: 2022, rating: 9.4, posterUrl: "https://image.tmdb.org/t/p/w500/qJgGMbPdeNPyWpsqN1NLK4CYzcc.jpg", slug: "elden-ring", synopsis: "Un Tarnied explore l'Entre-Terre pour devenir le Seigneur d'Elden.", genres: ["Action", "RPG", "Fantastique"] },
  { id: "g4", title: "God of War Ragnarök", type: "jeu", year: 2022, rating: 9.3, posterUrl: "https://image.tmdb.org/t/p/w500/84kQ4sijEKJb63nwQc6GqAs6LLH.jpg", slug: "god-of-war-ragnarok", synopsis: "Kratos et Atreus affrontent les dieux nordiques dans une épopée mythologique.", genres: ["Action", "Aventure"] },
  { id: "g5", title: "Cyberpunk 2077", type: "jeu", year: 2020, rating: 8.7, posterUrl: "https://image.tmdb.org/t/p/w500/jJqVv7kQaSP1L0wCfgqQqS5FlAz.jpg", slug: "cyberpunk-2077", synopsis: "Dans un futur dystopique, un mercenaire cherche un implant qui promet l'immortalité.", genres: ["Action", "RPG", "Science-Fiction"] },
  { id: "g6", title: "Red Dead Redemption 2", type: "jeu", year: 2018, rating: 9.7, posterUrl: "https://image.tmdb.org/t/p/w500/5yH5wYTG5doFV4H8MZwln6YODCC.jpg", slug: "red-dead-redemption-2", synopsis: "Un hors-la-loi tente de survivre dans l'Ouest américain à l'aube du XXe siècle.", genres: ["Action", "Aventure", "Western"] },
  { id: "g7", title: "Final Fantasy VII Rebirth", type: "jeu", year: 2024, rating: 9.2, posterUrl: "https://image.tmdb.org/t/p/w500/bCEkcmRj5dBmH4hQpyaOAe5Iubs.jpg", slug: "final-fantasy-vii-rebirth", synopsis: "Cloud et ses alliés poursuivent Sephiroth à travers le monde.", genres: ["RPG", "Aventure", "Fantastique"] },
];

export const mockBooks: Media[] = [
  { id: "b1", title: "Le Petit Prince", type: "book", year: 1943, rating: 9.0, posterUrl: "https://picsum.photos/seed/livrepetitprince/300/450", slug: "le-petit-prince", synopsis: "Un pilote tombé en panne dans le désert rencontre un mystérieux petit prince venu d'une autre planète.", genres: ["Famille", "Aventure"] },
  { id: "b2", title: "1984", type: "book", year: 1949, rating: 8.9, posterUrl: "https://picsum.photos/seed/livre1984/300/450", slug: "1984", synopsis: "Dans un régime totalitaire, Winston Smith tente de préserver son humanité face à la surveillance omniprésente du Big Brother.", genres: ["Science-Fiction", "Drame"] },
  { id: "b3", title: "Harry Potter à l'École des Sorciers", type: "book", year: 1997, rating: 9.1, posterUrl: "https://picsum.photos/seed/livreharrypotter/300/450", slug: "harry-potter-a-lecole-des-sorciers", synopsis: "Un orphelin découvre qu'il est un sorcier et intègre une école de magie légendaire.", genres: ["Fantastique", "Aventure", "Famille"] },
  { id: "b4", title: "Le Seigneur des Anneaux", type: "book", year: 1954, rating: 9.3, posterUrl: "https://picsum.photos/seed/livresda/300/450", slug: "le-seigneur-des-anneaux", synopsis: "Un hobbit entreprend un voyage périlleux pour détruire un anneau maléfique.", genres: ["Fantastique", "Aventure"] },
  { id: "b5", title: "Dune", type: "book", year: 1965, rating: 9.0, posterUrl: "https://picsum.photos/seed/livredune/300/450", slug: "dune-livre", synopsis: "Sur la planète désertique Arrakis, un jeune héritier se lève pour venger sa famille et contrôler l'épice.", genres: ["Science-Fiction", "Aventure"] },
  { id: "b6", title: "Les Misérables", type: "book", year: 1862, rating: 9.2, posterUrl: "https://picsum.photos/seed/livremiserables/300/450", slug: "les-miserables", synopsis: "L'épopée de Jean Valjean, un ancien bagnard, dans la France du XIXe siècle.", genres: ["Drame", "Histoire"] },
  { id: "b7", title: "Fondation", type: "book", year: 1951, rating: 8.7, posterUrl: "https://picsum.photos/seed/livrefondation/300/450", slug: "fondation", synopsis: "Un mathématicien prédit la chute de l'Empire galactique et crée une fondation pour préserver le savoir.", genres: ["Science-Fiction"] },
  { id: "b8", title: "Le Monde de Narnia", type: "book", year: 1950, rating: 8.5, posterUrl: "https://picsum.photos/seed/livrenarnia/300/450", slug: "le-monde-de-narnia", synopsis: "Des enfants découvrent un monde magique caché dans une armoire.", genres: ["Fantastique", "Aventure", "Famille"] },
];

export const mockNovels: Media[] = [
  { id: "n1", title: "Classroom of the Elite", type: "novel", year: 2015, rating: 8.6, posterUrl: "https://picsum.photos/seed/novelclassroom/300/450", slug: "classroom-of-the-elite", synopsis: "Dans une école d'élite où la compétition est impitoyable, un garçon cache ses véritables capacités.", genres: ["Drame", "Thriller"] },
  { id: "n2", title: "Mushoku Tensei", type: "novel", year: 2012, rating: 8.7, posterUrl: "https://picsum.photos/seed/novelmushoku/300/450", slug: "mushoku-tensei", synopsis: "Un homme réincarné dans un monde magique décide de vivre sa seconde vie sans aucun regret.", genres: ["Fantastique", "Aventure"] },
  { id: "n3", title: "Re:Zero", type: "novel", year: 2014, rating: 8.5, posterUrl: "https://picsum.photos/seed/novelrezero/300/450", slug: "re-zero", synopsis: "Un garçon transporté dans un monde fantastique découvre qu'il peut revenir à la vie après sa mort.", genres: ["Fantastique", "Drame", "Mystère"] },
  { id: "n4", title: "Overlord", type: "novel", year: 2012, rating: 8.4, posterUrl: "https://picsum.photos/seed/noveloverlord/300/450", slug: "overlord", synopsis: "Un joueur piégé dans un MMORPG décide de conquérir le monde en tant que sorcier squelette.", genres: ["Fantastique", "Action"] },
  { id: "n5", title: "That Time I Got Reincarnated as a Slime", type: "novel", year: 2013, rating: 8.5, posterUrl: "https://picsum.photos/seed/novelslime/300/450", slug: "tensei-slime", synopsis: "Un homme réincarné en slime dans un monde fantastique bâtit une nation d'êtres magiques.", genres: ["Fantastique", "Aventure", "Comédie"] },
  { id: "n6", title: "The Beginning After the End", type: "novel", year: 2017, rating: 8.8, posterUrl: "https://picsum.photos/seed/novelbeginning/300/450", slug: "the-beginning-after-the-end", synopsis: "Un roi puissant se réincarne dans un monde magique et recommence sa vie depuis le début.", genres: ["Fantastique", "Action", "Aventure"] },
  { id: "n7", title: "The Eminence in Shadow", type: "novel", year: 2018, rating: 8.3, posterUrl: "https://picsum.photos/seed/neveleminence/300/450", slug: "the-eminence-in-shadow", synopsis: "Un garçon qui se prend pour un génie du crime découvre que ses fantasmes sont bien réels.", genres: ["Comédie", "Action", "Fantastique"] },
];

export const mockWebtoons: Media[] = [
  { id: "w1", title: "Solo Leveling (Webtoon)", type: "webtoon", year: 2018, rating: 9.0, posterUrl: "https://image.tmdb.org/t/p/w500/geCRueV3ElhRTr0xtJuEWJt6dJ1.jpg", slug: "solo-leveling-webtoon", synopsis: "Le chasseur le plus faible devient le plus fort après avoir obtenu un système de quêtes unique.", genres: ["Action", "Fantastique"] },
  { id: "w2", title: "Tower of God", type: "webtoon", year: 2010, rating: 8.7, posterUrl: "https://image.tmdb.org/t/p/w500/7nR3QGDJgFkH6LRQVb6y76jB5PB.jpg", slug: "tower-of-god", synopsis: "Un garçon escalade une tour mystérieuse pour retrouver son amie.", genres: ["Action", "Aventure", "Fantastique"] },
  { id: "w3", title: "The God of High School", type: "webtoon", year: 2014, rating: 8.3, posterUrl: "https://image.tmdb.org/t/p/w500/vPTwGqkMBx1j9w5A65MAgZHMJCE.jpg", slug: "the-god-of-high-school", synopsis: "Des lycéens participent à un tournoi d'arts martiaux qui cache des enjeux bien plus grands.", genres: ["Action", "Arts Martiaux"] },
  { id: "w4", title: "Noblesse", type: "webtoon", year: 2007, rating: 8.4, posterUrl: "https://image.tmdb.org/t/p/w500/aCjKMgkxgkWnHMsY4iB4TMCvvxN.jpg", slug: "noblesse", synopsis: "Un noble vampire se réveille après 820 ans et s'adapte à la vie moderne.", genres: ["Action", "Fantastique", "Comédie"] },
];

export const allMockData: Media[] = [...mockTrending, ...mockFilms, ...mockSeries, ...mockAnimes, ...mockGames, ...mockBooks, ...mockNovels, ...mockWebtoons];

export function getMockByType(type: Media['type']): Media[] {
  switch (type) {
    case 'film': return mockFilms;
    case 'serie': return mockSeries;
    case 'anime': return mockAnimes;
    case 'jeu': return mockGames;
    case 'webtoon': return mockWebtoons;
    case 'book': return mockBooks;
    case 'novel': return mockNovels;
    default: return [];
  }
}
