// Overrides for the closed set of UI labels. These are short, ambiguous words
// ("Jeux", "Films", "À propos") that machine translation gets wrong out of
// context ("Games played", "Movie", "Who we are"). Free MT endpoints are also
// rate-limited, so quality would otherwise fluctuate with whichever engine
// answers. Keys are normalized: lowercase + accents stripped, so "Séries" and
// "Series" share one entry. Anything absent here falls through to live MT.

export type OverrideLang =
  | 'english'
  | 'spanish'
  | 'german'
  | 'italian'
  | 'portuguese'
  | 'japanese'
  | 'korean'
  | 'chinese_simplified'
  | 'russian'
  | 'arabic'
  | 'dutch'
  | 'polish'
  | 'turkish'
  | 'swedish'

export function normalizeKey(input: string): string {
  return input
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
}

const RAW: Record<OverrideLang, Record<string, string>> = {
  english: {
    'films': 'Movies',
    'series': 'TV series',
    'animes': 'Anime',
    'jeux': 'Games',
    'comics': 'Comics',
    'webtoons': 'Webtoons',
    'livres': 'Books',
    'light novels': 'Light Novels',
    'tv live': 'Live TV',
    'tout le divertissement, un seul endroit.': 'All entertainment in one place.',
    'recommandations': 'Recommendations',
    'voir tout': 'See all',
    'details': 'Details',
    'favoris': 'Favorites',
    'trier': 'Sort',
    'filtrer': 'Filter',
    'par defaut': 'Default',
    'titre': 'Title',
    'note': 'Rating',
    'annee': 'Year',
    'genre': 'Genre',
    'erreur de chargement': 'Loading error',
    'qui sommes-nous': 'Who we are',
    'liens utiles': 'Useful links',
    'accueil': 'Home',
    'a propos': 'About',
    'mentions legales': 'Legal notice',
    'contact': 'Contact',
    'categories': 'Categories',
    'livres & light novels': 'Books & Light Novels',
    '© 2026 tous droits reserves': '© 2026 All rights reserved',
  },
  spanish: {
    'films': 'Películas',
    'series': 'Series',
    'animes': 'Anime',
    'jeux': 'Juegos',
    'comics': 'Cómics',
    'webtoons': 'Webtoons',
    'livres': 'Libros',
    'light novels': 'Light Novels',
    'tv live': 'TV en vivo',
    'tout le divertissement, un seul endroit.': 'Todo el entretenimiento, en un solo lugar.',
    'recommandations': 'Recomendaciones',
    'voir tout': 'Ver todo',
    'details': 'Detalles',
    'favoris': 'Favoritos',
    'trier': 'Ordenar',
    'filtrer': 'Filtrar',
    'par defaut': 'Predeterminado',
    'titre': 'Título',
    'note': 'Calificación',
    'annee': 'Año',
    'genre': 'Género',
    'erreur de chargement': 'Error de carga',
    'qui sommes-nous': 'Quiénes somos',
    'liens utiles': 'Enlaces útiles',
    'accueil': 'Inicio',
    'a propos': 'Acerca de',
    'mentions legales': 'Aviso legal',
    'contact': 'Contacto',
    'categories': 'Categorías',
    'livres & light novels': 'Libros y light novels',
    '© 2026 tous droits reserves': '© 2026 Todos los derechos reservados',
  },
  german: {
    'films': 'Filme',
    'series': 'Serien',
    'animes': 'Anime',
    'jeux': 'Spiele',
    'comics': 'Comics',
    'webtoons': 'Webtoons',
    'livres': 'Bücher',
    'light novels': 'Light Novels',
    'tv live': 'Live-TV',
    'tout le divertissement, un seul endroit.': 'Gesamte Unterhaltung an einem einzigen Ort.',
    'recommandations': 'Empfehlungen',
    'voir tout': 'Alle ansehen',
    'details': 'Details',
    'favoris': 'Favoriten',
    'trier': 'Sortieren',
    'filtrer': 'Filtern',
    'par defaut': 'Standard',
    'titre': 'Titel',
    'note': 'Bewertung',
    'annee': 'Jahr',
    'genre': 'Genre',
    'erreur de chargement': 'Ladefehler',
    'qui sommes-nous': 'Wer wir sind',
    'liens utiles': 'Nützliche Links',
    'accueil': 'Startseite',
    'a propos': 'Über uns',
    'mentions legales': 'Impressum',
    'contact': 'Kontakt',
    'categories': 'Kategorien',
    'livres & light novels': 'Bücher & Light Novels',
    '© 2026 tous droits reserves': '© 2026 Alle Rechte vorbehouden',
  },
  italian: {
    'films': 'Film',
    'series': 'Serie',
    'animes': 'Anime',
    'jeux': 'Giochi',
    'comics': 'Fumetti',
    'webtoons': 'Webtoons',
    'livres': 'Libri',
    'light novels': 'Light Novel',
    'tv live': 'TV in diretta',
    'tout le divertissement, un seul endroit.': 'Tutto l’intrattenimento, in un unico posto.',
    'recommandations': 'Consigliati',
    'voir tout': 'Vedi tutto',
    'details': 'Dettagli',
    'favoris': 'Preferiti',
    'trier': 'Ordina',
    'filtrer': 'Filtra',
    'par defaut': 'Predefinito',
    'titre': 'Titolo',
    'note': 'Voto',
    'annee': 'Anno',
    'genre': 'Genere',
    'erreur de chargement': 'Errore di caricamento',
    'qui sommes-nous': 'Chi siamo',
    'liens utiles': 'Link utili',
    'accueil': 'Home',
    'a propos': 'Informazioni',
    'mentions legales': 'Note legali',
    'contact': 'Contatti',
    'categories': 'Categorie',
    'livres & light novels': 'Libri e light novel',
    '© 2026 tous droits reserves': '© 2026 Tutti i diritti riservati',
  },
  portuguese: {
    'films': 'Filmes',
    'series': 'Séries',
    'animes': 'Animes',
    'jeux': 'Jogos',
    'comics': 'Gibis',
    'webtoons': 'Webtoons',
    'livres': 'Livros',
    'light novels': 'Light Novels',
    'tv live': 'TV ao vivo',
    'tout le divertissement, un seul endroit.': 'Todo o entretenimento, em um só lugar.',
    'recommandations': 'Recomendações',
    'voir tout': 'Ver tudo',
    'details': 'Detalhes',
    'favoris': 'Favoritos',
    'trier': 'Ordenar',
    'filtrer': 'Filtrar',
    'par defaut': 'Padrão',
    'titre': 'Título',
    'note': 'Nota',
    'annee': 'Ano',
    'genre': 'Gênero',
    'erreur de chargement': 'Erro ao carregar',
    'qui sommes-nous': 'Quem somos',
    'liens utiles': 'Links úteis',
    'accueil': 'Início',
    'a propos': 'Sobre',
    'mentions legales': 'Aviso legal',
    'contact': 'Contato',
    'categories': 'Categorias',
    'livres & light novels': 'Livros e light novels',
    '© 2026 tous droits reserves': '© 2026 Todos os direitos reservados',
  },
  japanese: {
    'films': '映画',
    'series': 'ドラマ',
    'animes': 'アニメ',
    'jeux': 'ゲーム',
    'comics': 'コミック',
    'webtoons': 'ウェブトゥーン',
    'livres': '書籍',
    'light novels': 'ライトノベル',
    'tv live': 'ライブ配信',
    'tout le divertissement, un seul endroit.': 'すべてのエンターテインメントを、ひとつの場所に。',
    'recommandations': 'おすすめ',
    'voir tout': 'すべて見る',
    'details': '詳細',
    'favoris': 'お気に入り',
    'trier': '並べ替え',
    'filtrer': 'フィルター',
    'par defaut': 'デフォルト',
    'titre': 'タイトル',
    'note': '評価',
    'annee': '年',
    'genre': 'ジャンル',
    'erreur de chargement': '読み込みエラー',
    'qui sommes-nous': '私たちについて',
    'liens utiles': '便利なリンク',
    'accueil': 'ホーム',
    'a propos': 'このサイトについて',
    'mentions legales': '法的通知',
    'contact': 'お問い合わせ',
    'categories': 'カテゴリ',
    'livres & light novels': '書籍 & ライトノベル',
    '© 2026 tous droits reserves': '© 2026 無断転載禁止',
  },
  korean: {
    'films': '영화',
    'series': '드라마',
    'animes': '애니메이션',
    'jeux': '게임',
    'comics': '만화',
    'webtoons': '웹툰',
    'livres': '도서',
    'light novels': '라이트노벨',
    'tv live': '실시간 TV',
    'tout le divertissement, un seul endroit.': '모든 오락을 한 곳에서.',
    'recommandations': '추천',
    'voir tout': '전체 보기',
    'details': '상세 정보',
    'favoris': '즐겨찾기',
    'trier': '정렬',
    'filtrer': '필터',
    'par defaut': '기본값',
    'titre': '제목',
    'note': '평점',
    'annee': '연도',
    'genre': '장르',
    'erreur de chargement': '불러오기 오류',
    'qui sommes-nous': '우리 소개',
    'liens utiles': '유용한 링크',
    'accueil': '홈',
    'a propos': '소개',
    'mentions legales': '법적 고지',
    'contact': '문의',
    'categories': '카테고리',
    'livres & light novels': '도서 & 라이트노벨',
    '© 2026 tous droits reserves': '© 2026 모든 권리 보유',
  },
  chinese_simplified: {
    'films': '电影',
    'series': '电视剧',
    'animes': '动漫',
    'jeux': '游戏',
    'comics': '漫画',
    'webtoons': '条漫',
    'livres': '书籍',
    'light novels': '轻小说',
    'tv live': '直播',
    'tout le divertissement, un seul endroit.': '所有娱乐，一站俱全。',
    'recommandations': '推荐',
    'voir tout': '查看全部',
    'details': '详情',
    'favoris': '收藏',
    'trier': '排序',
    'filtrer': '筛选',
    'par defaut': '默认',
    'titre': '标题',
    'note': '评分',
    'annee': '年份',
    'genre': '类型',
    'erreur de chargement': '加载失败',
    'qui sommes-nous': '关于我们',
    'liens utiles': '实用链接',
    'accueil': '首页',
    'a propos': '简介',
    'mentions legales': '法律声明',
    'contact': '联系我们',
    'categories': '分类',
    'livres & light novels': '书籍与轻小说',
    '© 2026 tous droits reserves': '© 2026 版权所有',
  },
  russian: {
    'films': 'Фильмы',
    'series': 'Сериалы',
    'animes': 'Аниме',
    'jeux': 'Игры',
    'comics': 'Комиксы',
    'webtoons': 'Веб-комиксы',
    'livres': 'Книги',
    'light novels': 'Лайт-новеллы',
    'tv live': 'Прямой эфир',
    'tout le divertissement, un seul endroit.': 'Все развлечения в одном месте.',
    'recommandations': 'Рекомендации',
    'voir tout': 'Смотреть все',
    'details': 'Подробнее',
    'favoris': 'Избранное',
    'trier': 'Сортировать',
    'filtrer': 'Фильтр',
    'par defaut': 'По умолчанию',
    'titre': 'Название',
    'note': 'Рейтинг',
    'annee': 'Год',
    'genre': 'Жанр',
    'erreur de chargement': 'Ошибка загрузки',
    'qui sommes-nous': 'О нас',
    'liens utiles': 'Полезные ссылки',
    'accueil': 'Главная',
    'a propos': 'О проекте',
    'mentions legales': 'Правовая информация',
    'contact': 'Контакты',
    'categories': 'Категории',
    'livres & light novels': 'Книги и лайт-новеллы',
    '© 2026 tous droits reserves': '© 2026 Все права защищены',
  },
  arabic: {
    'films': 'أفلام',
    'series': 'مسلسلات',
    'animes': 'أنمي',
    'jeux': 'ألعاب',
    'comics': 'مانغا',
    'webtoons': 'ويبتونز',
    'livres': 'كتب',
    'light novels': 'روايات خفيفة',
    'tv live': 'بث مباشر',
    'tout le divertissement, un seul endroit.': 'كل الترفيه في مكان واحد.',
    'recommandations': 'توصيات',
    'voir tout': 'عرض الكل',
    'details': 'التفاصيل',
    'favoris': 'المفضلة',
    'trier': 'ترتيب',
    'filtrer': 'تصفية',
    'par defaut': 'افتراضي',
    'titre': 'العنوان',
    'note': 'التقييم',
    'annee': 'السنة',
    'genre': 'النوع',
    'erreur de chargement': 'خطأ في التحميل',
    'qui sommes-nous': 'من نحن',
    'liens utiles': 'روابط مفيدة',
    'accueil': 'الرئيسية',
    'a propos': 'حول الموقع',
    'mentions legales': 'إشعار قانوني',
    'contact': 'اتصل بنا',
    'categories': 'التصنيفات',
    'livres & light novels': 'كتب وروايات خفيفة',
    '© 2026 tous droits reserves': '© 2026 جميع الحقوق محفوظة',
  },
  dutch: {
    'films': 'Films',
    'series': 'Series',
    'animes': 'Anime',
    'jeux': 'Games',
    'comics': 'Strips',
    'webtoons': 'Webtoons',
    'livres': 'Boeken',
    'light novels': 'Light novels',
    'tv live': 'Live TV',
    'tout le divertissement, un seul endroit.': 'Alle entertainment op één plek.',
    'recommandations': 'Aanbevelingen',
    'voir tout': 'Alles bekijken',
    'details': 'Details',
    'favoris': 'Favorieten',
    'trier': 'Sorteren',
    'filtrer': 'Filteren',
    'par defaut': 'Standaard',
    'titre': 'Titel',
    'note': 'Rating',
    'annee': 'Jaar',
    'genre': 'Genre',
    'erreur de chargement': 'Laadfout',
    'qui sommes-nous': 'Over ons',
    'liens utiles': 'Nuttige links',
    'accueil': 'Home',
    'a propos': 'Over deze site',
    'mentions legales': 'Juridisch',
    'contact': 'Contact',
    'categories': 'Categorieën',
    'livres & light novels': 'Boeken & light novels',
    '© 2026 tous droits reserves': '© 2026 Alle rechten voorbehouden',
  },
  polish: {
    'films': 'Filmy',
    'series': 'Seriale',
    'animes': 'Anime',
    'jeux': 'Gry',
    'comics': 'Komiksy',
    'webtoons': 'Webtoony',
    'livres': 'Książki',
    'light novels': 'Light novels',
    'tv live': 'Telewizja na żywo',
    'tout le divertissement, un seul endroit.': 'Cała rozrywka w jednym miejscu.',
    'recommandations': 'Polecane',
    'voir tout': 'Zobacz wszystko',
    'details': 'Szczegóły',
    'favoris': 'Ulubione',
    'trier': 'Sortuj',
    'filtrer': 'Filtruj',
    'par defaut': 'Domyślnie',
    'titre': 'Tytuł',
    'note': 'Ocena',
    'annee': 'Rok',
    'genre': 'Gatunek',
    'erreur de chargement': 'Błąd ładowania',
    'qui sommes-nous': 'O nas',
    'liens utiles': 'Przydatne linki',
    'accueil': 'Strona główna',
    'a propos': 'O serwisie',
    'mentions legales': 'Informacja prawna',
    'contact': 'Kontakt',
    'categories': 'Kategorie',
    'livres & light novels': 'Książki i light novels',
    '© 2026 tous droits reserves': '© 2026 Wszelkie prawa zastrzeżone',
  },
  turkish: {
    'films': 'Filmler',
    'series': 'Diziler',
    'animes': 'Animeler',
    'jeux': 'Oyunlar',
    'comics': 'Çizgi romanlar',
    'webtoons': 'Webtoonlar',
    'livres': 'Kitaplar',
    'light novels': 'Light noveller',
    'tv live': 'Canlı TV',
    'tout le divertissement, un seul endroit.': 'Tüm eğlence, tek bir yerde.',
    'recommandations': 'Öneriler',
    'voir tout': 'Tümünü gör',
    'details': 'Detaylar',
    'favoris': 'Favoriler',
    'trier': 'Sırala',
    'filtrer': 'Filtrele',
    'par defaut': 'Varsayılan',
    'titre': 'Başlık',
    'note': 'Puan',
    'annee': 'Yıl',
    'genre': 'Tür',
    'erreur de chargement': 'Yükleme hatası',
    'qui sommes-nous': 'Biz kimiz',
    'liens utiles': 'Faydalı bağlantılar',
    'accueil': 'Ana sayfa',
    'a propos': 'Hakkımızda',
    'mentions legales': 'Yasal uyarı',
    'contact': 'İletişim',
    'categories': 'Kategoriler',
    'livres & light novels': 'Kitaplar ve light noveller',
    '© 2026 tous droits reserves': '© 2026 Tüm hakları saklıdır',
  },
  swedish: {
    'films': 'Filmer',
    'series': 'Serier',
    'animes': 'Anime',
    'jeux': 'Spel',
    'comics': 'Teckenserier',
    'webtoons': 'Webtoons',
    'livres': 'Böcker',
    'light novels': 'Light novels',
    'tv live': 'Direktsänd TV',
    'tout le divertissement, un seul endroit.': 'All underhållning på ett ställe.',
    'recommandations': 'Rekommendationer',
    'voir tout': 'Visa alla',
    'details': 'Detaljer',
    'favoris': 'Favoriter',
    'trier': 'Sortera',
    'filtrer': 'Filtrera',
    'par defaut': 'Standard',
    'titre': 'Titel',
    'note': 'Betyg',
    'annee': 'År',
    'genre': 'Genre',
    'erreur de chargement': 'Fel vid inläsning',
    'qui sommes-nous': 'Om oss',
    'liens utiles': 'Användbara länkar',
    'accueil': 'Hem',
    'a propos': 'Om webbplatsen',
    'mentions legales': 'Juridisk information',
    'contact': 'Kontakt',
    'categories': 'Kategorier',
    'livres & light novels': 'Böcker och light novels',
    '© 2026 tous droits reserves': '© 2026 Alla rättigheter förbehållna',
  },
}

const INDEXED = new Map<string, Map<string, string>>()

function indexFor(lang: string): Map<string, string> | undefined {
  if (lang === 'french') return undefined
  const cached = INDEXED.get(lang)
  if (cached) return cached
  const table = RAW[lang as OverrideLang]
  if (!table) return undefined
  const map = new Map<string, string>()
  for (const [key, value] of Object.entries(table)) map.set(normalizeKey(key), value)
  INDEXED.set(lang, map)
  return map
}

export function getOverride(lang: string, text: string): string | undefined {
  return indexFor(lang)?.get(normalizeKey(text))
}

export const OVERRIDE_LANGS = Object.keys(RAW) as OverrideLang[]
